### ISSUE TITLE
Precompiled header

### ISSUE THREAD

**Issue by winter-yuki** [winter-yuki/neuro-game#10]
Create precompiled header to reduce compilation time.

**Comment by NikitaS4** [comment]
I wanna take this one but at least I'd like to figure out some details of the task. Which libraries does the precompiled header include? And what about .pro-file? I mean qt-libraries considered to be included with this one, not with precompiled header (or this problem will be solved with another issue?)

**Comment by winter-yuki** [comment]
SLT headers should be there, some common-used Qt headers that are not precompiled already. This list will be updated dinamically, according to the purpose.

About .pro I don't clearly understand...

**Comment by NikitaS4** [comment]
Ok, understood.

In terms of .pro, there are some modules should be included by writing code into .pro file (for example, "QT += network" allows using network QT modules like Qudp, Qtcp, etc.)
You can see a similar example at the solution of issue #2

**Comment by NikitaS4** [comment]
Ok, understood.

In terms of .pro, there are some modules should be included by writing code into .pro file (for example, "QT += network" allows using network QT modules like Qudp, Qtcp, etc.)
You can see a similar example at the solution of issue #2

**Comment by re1nex** [comment]
Work with Nikita on this issuses

**Comment by NikitaS4** [comment]
It seems, we have finished.

**Comment by winter-yuki** [comment]
Thanks to Nikita, example can be found ![here](https://github.com/NikitaS4/neuro-game/commit/bf9106942402b818c18514274092df472c05c0a1).
