### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by winter-yuki** [winter-yuki/neuro-game#17]
Main and in-game menus. And switch between them.

**Comment by NikitaS4** [comment]
I'll take this issuses

**Comment by re1nex** [comment]
Исусе

**Comment by winter-yuki** [comment]
Nikita is responsible for this task. 
Time - until 16th april.

**Comment by winter-yuki** [comment]
Nek has some problems with qt, re1nex, please, catch up.

**Comment by NikitaS4** [comment]
"Solved" problem, see latest PR

**Comment by winter-yuki** [comment]
Nek, it's time to get our interface to suitable condition. Time until end of this week will be enought, I think. And before it is needed to test methods of C++ call  from QML. In last project version there were examples. Nothing changed in gereral, I think, but nevertheless.
