### ISSUE TITLE
How to implement multiplayer

### ISSUE THREAD

**Issue by winter-yuki** [winter-yuki/neuro-game#2]
Find out potential ways to implement multiplayer in game.

**Comment by NikitaS4** [comment]
Я в деле!!!!!

**Comment by NikitaS4** [comment]
* I'm in

**Comment by re1nex** [comment]
Work with NikitaS4 on this problem

**Comment by winter-yuki** [comment]
Great! I rely on you. Next sunday we'll discuss results.

**Comment by winter-yuki** [comment]
And let's suppose that we have machines in one local network.

Also it will be great to have small example of code.

**Comment by NikitaS4** [comment]
Well, does it mean we are to "commit", for example, "hello-world" program to deal with it or smth else?

**Comment by winter-yuki** [comment]
Maybe. If you send this "hello world" from one computer to another and vice versa.

**Comment by winter-yuki** [comment]
PR your examples to "net" branch please.

**Comment by re1nex** [comment]
Ok ,there is simple example which was made on QT creator
[Client.zip](https://github.com/winter-yuki/neuro-game/files/3023843/Client.zip)
[server.zip](https://github.com/winter-yuki/neuro-game/files/3023844/server.zip)

**Comment by winter-yuki** [comment]
Great! Please, PR it to dev branch to "multiplayer" directory.
