### ISSUE TITLE
Racket animation

### ISSUE THREAD

**Issue by winter-yuki** [winter-yuki/neuro-game#29]
At the next stage we will need racket moving system. Trajectories, time to start moving that depends on ball position.

**Comment by winter-yuki** [comment]
It  is needed to have first thoughts until next week.

**Comment by winter-yuki** [comment]
It should be method in class Racket

**Comment by NadiaKH** [comment]
I will deal with it

**Comment by winter-yuki** [comment]
Two different animations is needed
