### ISSUE TITLE
Presentation water

### ISSUE THREAD

**Issue by winter-yuki** [winter-yuki/neuro-game#3]
Write initial words in presentation as in "about" doc.

**Comment by winter-yuki** [comment]
Everybody should choose part to tell about at the end, and make appropriate part of presentation.

**Comment by winter-yuki** [comment]
Write here your  preferences.

**Comment by winter-yuki** [comment]
Возьмите по теме:
- актуальность
- продукт проекта
- целевая аудитория и цели проекта
- предлагаемое решение и преимущества

Подожду пару дней, оставшееся сам раздам.

**Comment by winter-yuki** [comment]
Everything in branch dev.

**Comment by winter-yuki** [comment]
I'll get last item 4th.

**Comment by winter-yuki** [comment]
Don't forget about 17th.
And we have to create another instance of presentation for 19th.

**Comment by winter-yuki** [comment]
Ребята, добрый день!
19.04.2019 - это пятница - скорее всего, меня не будет в Питере.
Я попросил команду ОПД перенести нашу встречу на четверг 18.04.2019
Как только получу подтверждение о переносе встречи на 18.04.2019 - дам знать


Best regards,
Gennadii V. Kovalenko, PhD (doctorate in economics)
partner of Innovative Brain Solutions, 500 Startups member,  USA phone: +1 (202) 660-4552
whatsapp, phone: +7 (952) 217-18-98 tlg: @papercom  skype: papercom

**Comment by re1nex** [comment]
Issue
