### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by winter-yuki** [winter-yuki/neuro-game#5]
Obj models and textures in png: 
+ ball
+ table
+ lattice 
+ racket.
+ room

**Comment by Rest133** [comment]
Take this one.

**Comment by winter-yuki** [comment]
Eugeniy already works on it. Please contact with him for collaboration.

**Comment by winter-yuki** [comment]
Eugeniy, compose the scene until monday.

**Comment by winter-yuki** [comment]
It is done in general
